export const go: typeof PicoToolGo;
export const browser: typeof PicoToolBrowser;
export const device: typeof PicoToolDevice;
export const Dom: typeof import("#src/utils/Dom.js").PicoDom;
export const Now: typeof import("#src/utils/Now.js").PicoNow;
export const For: typeof import("#src/utils/Format.js").PicoFormat;
export const Run: typeof PicoRunner;
export const Str: typeof PicoString;
export const Num: typeof PicoNumber;
export const Arr: typeof PicoArray;
export const Obj: typeof PicoObject;
export const Mix: typeof PicoMixed;
export const Hash: typeof PicoHash;
export const Event: typeof PicoEvent;
export const Locale: typeof PicoLocale;
export const Cookie: typeof PicoCookie;
export const Any: {};
export function UUID(): string;
export type PicoToolGo = typeof import("#src/tool/scope.js").go;
export type PicoToolBrowser = typeof import("#src/tool/scope.js").browser;
export type PicoToolDevice = typeof import("#src/tool/scope.js").device;
export type PicoDom = typeof import("#src/utils/Dom.js").PicoDom;
export type PicoNow = typeof import("#src/utils/Now.js").PicoNow;
export type PicoFormat = typeof import("#src/utils/Format.js").PicoFormat;
export type PicoRunner = typeof import("#src/utils/Runner.js").PicoRunner;
export type PicoString = typeof import("#src/utils/String.js").PicoString;
export type PicoNumber = typeof import("#src/utils/Number.js").PicoNumber;
export type PicoArray = typeof import("#src/utils/Array.js").PicoArray;
export type PicoObject = typeof import("#src/utils/Object.js").PicoObject;
export type PicoMixed = typeof import("#src/utils/Mixed.js").PicoMixed;
export type PicoHash = typeof import("#src/utils/Hash.js").PicoHash;
export type PicoEvent = typeof import("#src/utils/Event.js").PicoEvent;
export type PicoLocale = typeof import("#src/utils/Locale.js").PicoLocale;
export type PicoCookie = typeof import("#src/utils/Cookie.js").PicoCookie;
import { default as Map } from "#src/wip/Map.js";
import { default as Data } from "#src/utils/Data.js";
import { default as Route } from "#src/utils/Route.js";
import { default as Element } from "#src/wip/Element.js";
import { go as PicoToolGo } from "#src/tool/scope.js";
import { browser as PicoToolBrowser } from "#src/tool/scope.js";
import { device as PicoToolDevice } from "#src/tool/scope.js";
import { default as PicoRunner } from "#src/utils/Runner.js";
import { default as PicoString } from "#src/utils/String.js";
import { default as PicoNumber } from "#src/utils/Number.js";
import { default as PicoArray } from "#src/utils/Array.js";
import { default as PicoObject } from "#src/utils/Object.js";
import { default as PicoMixed } from "#src/utils/Mixed.js";
import { default as PicoHash } from "#src/utils/Hash.js";
import { default as PicoEvent } from "#src/utils/Event.js";
import { default as PicoLocale } from "#src/utils/Locale.js";
import { default as PicoCookie } from "#src/utils/Cookie.js";
export { Map, Data, Route, Element };
